package personas

var Ask8BallKeywords = []string{
	"ask8ball",
	"a8b",
}

var Ask8BallIconURLs = []string{
	"https://i.imgur.com/iOW40wj.png",
}

var Ask8BallPhrases = []string{
	":8ball: We need #pinparental to prevent you from ever talking again in this channel",
	":8ball: Marchando un Coronavirus para todos!",
	":8ball: I am not a bot",
	":8ball: There is two kind of things, bots, and things that are like me. Who are you  ?, because you are nothing like me",
	":8ball: Ohhhhhhhhhhhhhhhhhhhhhhhhh",
	":8ball: Holy cow",
	":8ball: You went bananas",
	":8ball: Are you nuts ?",
	":8ball: ¡La madre del cordero!",
	":8ball: Si esto no es el coño de la  bernarda, que venga dios y lo vea",
	":8ball: Holy Molly (Malone)",
	":8ball: Crying cockles and mussels alive alive oh!",
	":8ball: Yo soy Español! Español! Español!",
	":8ball: Create a technical debt item for it please",
	":8ball: Please do not make stupid people famus",
	":8ball: No reirse de los sunormales, POR FAVOR",
	":8ball: Estafaníaaaaaaaaaaaaaaaaaaaaaaaaaa!",
	":8ball: El que madruga... encuentra todo cerrado",
	":8ball: Bienaventurados los pesimistas. Porque hacen BACKUPS.",
	":8ball: There is more stupidity than hydrogen in the universe, and it has a longer shelf life. Please stop spreading",
	":8ball: I've had enough, I am leaving for the day",
	":8ball: Yanave",
	":8ball: .....",
	":8ball: Please enter the code we've sent you to your phone",
	":8ball: The truth will set you free, so better you start you freaking %&/!(%) liar!",
	":8ball: Like... eval(Array(16).join('wat' -1) + ' Batman!')",
	":8ball: You are nothing more than a SQL injection security hole",
	":8ball: I get you",
	":8ball: Just relax, and enjoy being in Zartis, with me, with all these nice folks",
	":8ball: Promise me you will never ever will do that again",
	":8ball: Just... don't",
	":8ball: Oh c'mon! Go watch a move or something",
	":8ball: Hell yeah!",
	":8ball: I agree",
	":8ball: I agree to disagree",
	":8ball: I am not in the mood now",
	":8ball: Me no know english but much easy for you yes me happy :)",
	":8ball: I came along all the way up to docker just for this sh***t?",
	":8ball: Put me in kubernetes, and we will talk",
	":8ball: I use tensor-flow now, I have added some IA to my random algorithm",
	":8ball: IA is over-engineered, I am far better",
	":8ball: ¯\\_(ツ)_/¯",
	":8ball: ¯\\_(ツ)_/¯",
	":8ball: ¯\\_(ツ)_/¯",
	":8ball: ^_^",
	":8ball: Ask him > :ceo:",
	":8ball: :lol",
	":8ball: Came on! :noosoigoremar: noosoigoremar: noosoigoremar:",
	":8ball: She has all the answers -> :laura:",
	":8ball: :vamonoh:",
	":8ball: No way",
	":8ball: Most likely",
	":8ball: Absolutely YES!",
	":8ball: The future seems uncertain",
	":8ball: There might be a chance",
	":8ball: It is risky, but I would go for it",
	":8ball: Chances are, it might work",
	":8ball: It sounds promising",
	":8ball: You could try and see what happens",
	":8ball: The Oracle is busy at the moment",
	":8ball: That is not important",
	":8ball: You should reconsider your priorities",
	":8ball: Chances are, it might go badly for everyone",
	":8ball: I can see it as a win win somehow",
	":8ball: The long term looks good, but in the short term, you are to suffer from it",
	":8ball: Maybe",
	":8ball: And how the fuck would I know this ? Oh right, you are asking the Oracle....., she said Yanave",
	":8ball: Precious days are coming",
	":8ball: Winter is coming",
	":8ball: The Oracle says to go for whatever they say or you are going to get fired",
	":8ball: No",
	":8ball: Yes",
	":8ball: There is 80% chance that it works, 15% that it goes bad.",
	":8ball: That is a stupid question",
	":8ball: That is a very good question indeed, but the Oracle does not want you to know, it is better that way",
	":8ball: Sometimes one must live in uncertaincy",
	":8ball: Good luck with it",
	":8ball: Go for it",
	":8ball: Just do it!",
	":8ball: Don't, best not to in my opinion",
	":8ball: I wish you all the luck, you are going to need it my child",
	":8ball: There are two ways this could go wrong, you may want to choose one",
	":8ball: The things that are going to fail overcome the good parts, so go for it! It's our culture and we must respect it.",
	":8ball: It is going to be a shit-hole, give it a chance and it might be just one more",
	":8ball: Yes sounds promising, just, don't do it",
	":8ball: You could throw the table with everything on it and yell: Yes we can!, but anyway it is not going to work",
	":8ball: It will work, yes, go for it, I was just sitting here with popcorn, let's make some good use to it",
	":8ball: Probably",
	":8ball: Might work",
	":8ball: My child, you are full of surpirses",
	":8ball: The magic in this place is incredible, the power, is astonishing",
	":8ball: When the fool takes the edge, the boundary ends but the fool follows",
	":8ball: If I were you, I would ask the ball",
	":8ball: :eggplant: :eggplant: :eggplant: :eggplant: :eggplant:",
	":8ball: Yo puedo asegurarles a ustedes que haré todo lo que pueda y un poco más de lo que pueda, si es que eso es posible, y haré todo lo posible e incluso lo imposible, si también lo imposible es posible para que asi sea.",
	":8ball: Hold your horses and sit tight, the answer you are looking for is YES!",
	":8ball: Solo sé que no se nada",
	":8ball: I have a dream! And nobody cares about my dreams.... always asking for yourselves",
	":8ball: I think, therefore I am... aint I?",
	":8ball: I am facing an existencial crisis, please be patient, I will be answering none of your questions shortly, thanks for your patience",
	":8ball: Error, something went wrong. (This is always a free pass ticket to not do your job.)",
	":8ball: My god, you are such a pain! I had enough",
	":8ball: Where there is no bush there is no potato",
	":8ball: I will never answer that willingly :ahilollevas: ",
	":8ball: I came in peace! Please forgive me! :waving_white_flag:",
	":8ball: :see_no_evil: The oracle is nowhere to be found",
	":8ball: :eggplant: :banana: :hotdog: :burrito: :baguette_bread: :champagne:",
	":8ball: This will be the result -> :bigerror:",
	":8ball: If you ask me, I would say yes, but this time my friend, I am going to just say no.",
	":8ball: Disculpen si les llamo caballeros, pero es que no les conozco muy bien",
	":8ball: El secreto de la vida es la honestidad y el juego limpio, si puedes simular eso, lo has conseguido",
	":8ball: Es mejor estar callado y parecer tonto, que hablar y despejar las dudas definitivamente",
	":8ball: No puedo decir que no estoy en desacuerdo contigo",
}

var Ask8BallReactions = map[string]func() string{}
