package personas

var Ask8BallKeywords = []string{
	"ask8ball",
	"a8b",
}

var Ask8BallIconURLs = []string{
	"https://i.imgur.com/iOW40wj.png",
}

var Ask8BallPhrases = []string{
	"No way",
	"Most likely",
	"Absolutely YES!",
	"The future seems uncertain",
	"There might be a chance",
	"It is risky, but I would go for it",
	"Chances are, it might work",
	"It sounds promising",
	"You could try and see what happens",
	"The Oracle is busy at the moment",
	"That is not important",
	"You should reconsider your priorities",
	"Chances are, it might go badly for everyone",
	"I can see it as a win win somehow",
	"The long term looks good, but in the short term, you are to suffer from it",
	"Maybe",
	"And how the fuck would I know this ? Oh right, you are asking the Oracle....., she said Yanave",
	"Precious days are coming",
	"Winter is coming",
	"The Oracle says to go for whatever they say or you are going to get fired",
	"No",
	"Yes",
	"There is 80% chance that it works, 15% that it goes bad.",
	"That is a stupid question",
	"That is a very good question indeed, but the Oracle does not want you to know, it is better that way",
	"Sometimes one must live in uncertaincy",
	"Good luck with it",
	"Go for it",
	"Just do it!",
	"Don't, best not to in my opinion",
	"I wish you all the luck, you are going to need it my child",
	"There are two ways this could go wrong, you may want to choose one",
	"The things that are going to fail overcome the good parts, so go for it! It's our culture and we must respect it.",
	"It is going to be a shit-hole, give it a chance and it might be just one more",
	"Yes sounds promising, just, don't do it",
	"You could throw the table with everything on it and yell: Yes we can!, but anyway it is not going to work",
	"It will work, yes, go for it, I was just sitting here with popcorn, let's make some good use to it",
	"Probably",
	"Might work",
	"My child, you are full of surpirses",
	"The magic in this place is incredible, the power, is astonishing",
	"When the fool takes the edge, the boundary ends but the fool follows",
	"If I were you, I would ask the ball",
	":eggplant: :eggplant: :eggplant: :eggplant: :eggplant:",
	"Yo puedo asegurarles a ustedes que haré todo lo que pueda y un poco más de lo que pueda, si es que eso es posible, y haré todo lo posible e incluso lo imposible, si también lo imposible es posible para que asi sea.",
	"Hold your horses and sit tight, the answer you are looking for is YES!",
	"Solo sé que no se nada",
	"I have a dream! And nobody cares about my dreams.... always asking for yourselves",
	"I think, therefore I am... aint I?",
	"I am facing an existencial crisis, please be patient, I will be answering none of your questions shortly, thanks for your patience",
	"Error, something went wrong. (This is always a free pass ticket to not do your job.)",
	"My god, you are such a pain! I had enough",
	"Where there is no bush there is no potato",
	"I will never answer that willingly :ahilollevas: ",
	"I came in peace! Please forgive me! :waving_white_flag:",
	":see_no_evil: The oracle is nowhere to be found",
	":eggplant: :banana: :hotdog: :burrito: :baguette_bread: :champagne:",
	"This will be the result -> :bigerror:",
	"If you ask me, I would say yes, but this time my friend, I am going to just say no.",
}

var Ask8BallReactions = map[string]func() string{}
